export const START_SEARCH = "search.START_SEARCH";
export const SET_SEARCH_RESULT = "search.SET_SEARCH_RESULT";
export const STORE_SEARCH_TEXT = "search.STORE_SEARCH_TEXT";
export const GET_POPULAR_QUESTION_BY_AUTHOR =
  "search.GET_POPULAR_QUESTION_BY_AUTHOR";
export const GET_POPULAR_QUESTION_BY_TAG = "search.GET_POPULAR_QUESTION_BY_TAG";
export const SELECT_AUTHOR = "search.SELECT_AUTHOR";
export const SELECT_TAG = "search.SELECT_TAG";
export const SEARCH_META_INFO = "search.SEARCH_META_INFO";
export const LOAD_MORE_RESULT_DATA = "search.LOAD_MORE_RESULT_DATA";
export const SEARCH_META_INFO_ADDITION_INFO =
  "search.SEARCH_META_INFO_ADDITION_INFO";
