export const SET_POPULAR_TYPE = "search.SET_POPULAR_TYPE";
export const SET_POPULAR_NAME = "search.SET_POPULAR_NAME";
export const SET_AUTHOR_DATA = "search.SET_AUTHOR_DATA";
export const SHOW_QUESTION_INFO = "search.SHOW_QUESTION_INFO";
export const SHOW_ADDITION_INFO = "search.SHOW_ADDITION_INFO";
export const GET_POPULAR_ANSWERS = "search.GET_POPULAR_ANSWERS";
export const GET_SELECT_QUESTION_TITLE = "search.GET_SELECT_QUESTION_TITLE";
export const GET_SELECT_QUESTION_ID = "search.GET_SELECT_QUESTION_ID";
export const HAS_NEXT_QUESTION_ANSWER = "search.HAS_NEXT_QUESTION_ANSWER";
export const SEARCH_META_INFO_QUESTION_INFO =
  "search.SEARCH_META_INFO_QUESTION_INFO";
